#!/bin/sh

# 不支援 binary 的更新！要重新命名後上傳。
if [ $# -ge 2 ]; then
	fname="$(echo "$2" | sed 's!.\+/!!')"
	ghupload upload -m "$1"  "$2" "loaxsc/ghdrive/$fname" && \
	echo "\nwget -q https://raw.githubusercontent.com/loaxsc/ghdrive/main/$fname\n"
elif [ $# -eq 1 ]; then
	fname="$(echo "$1" | sed 's!.\+/!!')"
	ghupload upload -m "upload $fname"  "$1" "loaxsc/ghdrive/$fname" && \
	echo "\nwget -q https://raw.githubusercontent.com/loaxsc/ghdrive/main/$fname\n"
else
	echo 'ghdrive-upload "file"\nghdrive-upload "commit message" "file"'
fi
